### ISSUE TITLE
Max iterations (=1000) during X axis label placement reached

### ISSUE THREAD

**Issue by impredicative** [JeroenDelcour/tplot#26]
I'm seeing this printed just before a plot is generated:

```
tplot/utils.py:160: UserWarning: Max iterations (=1000) during X axis label placement reached.
  warn(
```

I'm afraid it's not a useful message. I'm not doing anything unreasonable, so `tplot` should ideally work without this warning.

I had just 13 data points. I guess `tplot` was trying to plot either too many x-axis values, and/or too closely, and/or with too many decimal places. The warning actually went away with 14 data points; it now shows one less decimal place for each label. Still, it would be better if it didn't happen.

**Comment by JeroenDelcour** [comment]
Looks like you've found a case where it gets stuck in an infinite loop while trying to fit in all the labels for the X axis. That should never happen, so it's definitely a bug. I put in that error message just so if it ever happened, at least it would tell you something's wrong instead of just running forever.

Could you post a minimum reproducible code example that generates this error?

**Comment by JeroenDelcour** [comment]
Should be fixed with the new release. Turns out it was an instability in the optimization loop caused by too big of a step size.

I also lowered the number of X ticks being drawn to prevent the labels from crowding too much.
